### ISSUE TITLE
UIが小さくて操作しにくい

### ISSUE THREAD

**Issue by Hackgets** [kawasawa/MyPad#1]
全体的にフォントやツールバーのアイコンなど、UIが小さくて操作しにくいです。いきなりわがままな要望をして申し訳ないですが、今一番期待しているテキストエディタなので、ついお節介を焼いてしまいました。

**Comment by kawasawa** [comment]
とんでもございません。ご期待下さりありがとうございます。  

これまでUI自体のサイズ変更は考慮されていませんでした。（変更できるのはフォントサイズのみ）
このご提案を機に可変対応できるか検討してみます。  

※
なお、これまでメニューバーやツールバーのUIは、老舗のサクラエディタやMicrosoft社の製品を参考にしておりました。
しかしながらこうして眺めてみますと、どれも全体的に配置が細かく、見やすさに欠いたものも見受けられますね。
<img width="467" alt="image" src="https://user-images.githubusercontent.com/16559662/161374177-fc8032fa-c62e-4d03-9e85-85ada2f00567.png">

**Comment by Hackgets** [comment]
本文のフォントサイズを大きくしたい人は、UIの文字も小さいと不便だろうと思ったんですね。あともう一つ気づいたんですが、拡大のショートカットキーの + にテンキーが使えないのは意図的なものでしょうか？

**Comment by kawasawa** [comment]
> あともう一つ気づいたんですが、拡大のショートカットキーの + にテンキーが使えないのは意図的なものでしょうか？

現象確認しました。意図した動作ではありませんでした。
こちら、テンキーからの入力に対応するよう修正します。

**Comment by kawasawa** [comment]
@Hackgets 
UIサイズの変更機能を追加し、v1.16.0 としてリリースしました。
現在 Microsoft Store の審査中で、2-3日ほどで置き換わると思います。
※本機能は影響範囲が広いため、今後も微調整が入る可能性があります。

![small](https://user-images.githubusercontent.com/16559662/162598638-a07fe0e2-0530-4d96-bcaf-39d1abc381c6.jpg)
![large](https://user-images.githubusercontent.com/16559662/162598644-d6a3c7f1-c0ce-4cf4-8cbf-4cb78396704c.jpg)

**Comment by Hackgets** [comment]
動作することを確認しました。ありがとうございます。
