### ISSUE TITLE
英数字の等幅半角字形に対応して欲しい

### ISSUE THREAD

**Issue by Hackgets** [kawasawa/MyPad#2]
OpenTypeには等幅半角字形 (hwid) という機能があり、英数字にそれを用いて、全ての文字が等幅ではない日本語フォントを等幅フォントのように扱う事の出来るテキストエディタがあります。選択肢の狭い日本語フォントにおいては有益な機能だと思います。

**Comment by Hackgets** [comment]
参考として、Meryの実装を挙げます。
https://www.haijin-boys.com/software/mery/mery-3-3-0#5
https://www.haijin-boys.com/software/mery/mery-3-3-0#7

**Comment by kawasawa** [comment]
@Hackgets 
まだ挙動が安定していないため、リリースまで至らず恐縮です。
それらしい動きにはなってきました。いずれも「メイリオ」で検証中です。

- 対応前
![before](https://user-images.githubusercontent.com/16559662/164744852-4ec743a7-5567-4901-ab37-763d54c10fbe.jpg)

- 対応後
![after](https://user-images.githubusercontent.com/16559662/164744102-9369f359-d435-4bdd-9ab8-dc65129bf1c6.jpg)

**Comment by Hackgets** [comment]
お手数をおかけしています。日本語の等幅フォントはオープンソースのものも結構あるのですが、コーディングに特化していて逆に使いにくかったりで…IBM Plexに期待してるんですが、どうもプロジェクトが停滞しているようです。

**Comment by Hackgets** [comment]
1.19.0において正常に動作していることを確認しました。よってクローズとさせていただきます。ありがとうございました。
