### ISSUE TITLE
起動がもっさりしている。

### ISSUE THREAD

**Issue by Hackgets** [kawasawa/MyPad#3]
ログビューワーを見ると、アプリの開始からファイルを読み込むまで5.5秒ほどかかっています。シンプルな機能のテキストエディタとしては重く感じます。以下に僕の環境を付記します。

MyPad 1.16.0
プロセッサ	AMD Ryzen 5 2400G with Radeon Vega Graphics 3.60 GHz
実装RAM 8.00 GB (6.93 GB 使用可能)
システムの種類 64 ビット オペレーティング システム、x64 ベース プロセッサ
エディション Windows 10 Home
バージョン	21H2
インストール日 ‎2022/‎01/‎17
OS ビルド 19044.1620
エクスペリエンス Windows Feature Experience Pack 120.2212.4170.0

**Comment by kawasawa** [comment]
@Hackgets 

本件、調整を行いました。次回のアップデートに含める予定です。

- 起動が重い一因
本アプリはダイアログ等を用いない1ページ型の構造を取っております。
あらゆるコンテンツが一画面に集約される一方で、初期表示の描画に時間がかかる傾向がありました。

- 今回行った調整
起動直後には必要無いコンテンツ（オプション画面等）の初期処理を遅延させることで、アプリの起動速度の改善を試みました。

- これに伴う懸念
初期処理が行われなかったコンテンツは、表示される直前に初期化されます。
例えば、オプション画面は、初めて表示する際の描画が遅れる可能性があります。
しかしながら、このデメリットよりも起動速度の改善による恩恵の方が大きいと判断しました。

**Comment by Hackgets** [comment]
一つ気になる現象を見つけたのですが、オプションで通知領域の常駐を無効にしていても、起動時に通知アイコンが一瞬表示されて消えるという挙動をします。もしこれが起動時間を増加させているなら、回避していただけないでしょうか。

個人的には、メモリを消費する常駐アプリは、そうせざるを得ない場合を除いて使用したくないものです。MyPadは常駐時にも100MB強のメモリを使用しており、やはりシンプルな機能のテキストエディタとしては過大に見えます。

**Comment by kawasawa** [comment]
@Hackgets 

> 起動時に通知アイコンが一瞬表示されて消える

はい、仰る通りです。通知領域アイコンは常駐せず凍結していますが、確かに存在します。
これは、トースト通知（旧バルーン通知）発行機能が通知領域アイコンと一体になっているためです。
この制約は本アプリが依存する [サードパーティー](https://github.com/HavenDV/H.NotifyIcon) に由来します。

> もしこれが起動時間を増加させているなら、回避していただけないでしょうか。

中期的な課題とさせてください。
ご推察の通りで、起動の負荷となっています。
先の項の通り、トースト通知と通知領域アイコンは癒着しており、
可能であればをこれらを分離したいのですが、付け焼き刃では行きませんでした。

しかしながら、
本アプリの開発初期にはかなり限定的であったトースト通知の手法が、
今現在はMicrosoftから公式に新たなアクセス方法が提供されています。
まだ実験できておらず確実ではありませんが、まとまった時間が取れるタイミングでトライさせてください。

> MyPadは常駐時にも100MB強のメモリを使用

対応が難しいのが現状です。
こちらはデザイン部分に引き摺られています。

本アプリは、このプラットフォームではデファクトスタンダードとなっている
[MahApps](https://mahapps.com) と呼ばれるデザイン基盤に乗せて作られています。
モダンで統一されたデザインを構築できる反面、少々メモリを占有します。
より軽量な規格があれば置き換えたいところですが、現時点では代替案が挙げられません。

**Comment by Hackgets** [comment]
起動時間の短縮については技術的な問題があり、また解決可能であることを理解しました。また僕はMyPadの先進的なデザインを気に入っており、そのためにメモリ消費が増えることはやむを得ないと考えます（日本語向けのテキストエディタの多くは、デザインに対してあまりに保守的です。）。従って、クローズとさせていただきます。
