### ISSUE TITLE
How to change font-weight

### ISSUE THREAD

**Issue by abdeljalil09** [kawasawa/MyPad#4]

**Comment by Hackgets** [comment]
最近はウェイト展開の多い日本語フォントも増えているので、有用な機能だと思います。フォントレンダリングの方法（そう言えば、ClearTypeが強めにかかっている気が…）にもよりますが、人によって読みやすい太さは違いますからね。

**Comment by kawasawa** [comment]
@abdeljalil09 

Thank you for your question.

Previously there was no setting to change the font weight.
We will provide a feature to resolve this issue in the next update.

It will look like the image below.
<img width="638" alt="fontweight" src="https://user-images.githubusercontent.com/16559662/163659575-ca5e5e2f-a955-4642-a993-f11b2b67cabe.png">
