### ISSUE TITLE
UIに使われているフォントを変更したい

### ISSUE THREAD

**Issue by Hackgets** [kawasawa/MyPad#6]
僕はWindowsのシステムフォントがどうも好きになれません。変更する方法が無いわけではないですが、場合によってレンダリングが汚かったり、UIが崩れる（UI用フォントを前提に設計されてるせい）で渋々メイリオUIを使っています。ただ、よく使うアプリのUIについてはこだわりたい気持ちがあります。これは当然MyPadのUIに関わることなので、技術的に困難かもしれませんが、ご検討いただけると幸いです。

**Comment by kawasawa** [comment]
@Hackgets 
お待たせしております。本件、次回のアップデートにて対応されます。
なお、こちらの機能は既存のテキストエディタのフォント変更とは別に設けられております。
（既存のフォント設定は "テキストエディタ" タブに移りました。）

![スクリーンショット 2022-05-18 221201](https://user-images.githubusercontent.com/16559662/169046907-14fc2812-62b4-49e6-b0b4-8c3f8b6ba781.jpg)

**Comment by Hackgets** [comment]
行間の広いフォントにすると、メニューがはみ出てしまいます。ちなみにフォントは IBM Plex Sans JP です。
![スクリーンショット 2022-05-19 161553](https://user-images.githubusercontent.com/102782728/169234138-7a009430-dd97-4347-ae28-b06a0aa17b1f.png)
